border_width = 2
margin = [4, 4]
default_border_color = "#050F07"
floating_border_color = "#5EDCEC"
focused_border_color = "#c6e5e6"


col1 = "#157590"
col2 = "#507390"
col3 = "#1293A2"
col4 = "#43B2B9"
col5 = "#21D2E9"
col6 = "#5EDCEC"
col7 = "#c6e5e6"
col8 = "#8aa0a1"
col9 = "#157590"
col10 = "#507390"
col11 = "#1293A2"
col12 = "#43B2B9"
col13 = "#21D2E9"
col14 = "#5EDCEC"
col15 = "#c6e5e6"



background = "#050F07"
foreground = "#c6e5e6"
