border_width = 2
margin = [4, 4]
default_border_color = "#221c16"
floating_border_color = "#BAC4B8"
focused_border_color = "#e2dbce"


col1 = "#C99E6A"
col2 = "#7B8384"
col3 = "#B6A78D"
col4 = "#CBB18F"
col5 = "#CEBCA1"
col6 = "#BAC4B8"
col7 = "#e2dbce"
col8 = "#9e9990"
col9 = "#C99E6A"
col10 = "#7B8384"
col11 = "#B6A78D"
col12 = "#CBB18F"
col13 = "#CEBCA1"
col14 = "#BAC4B8"
col15 = "#e2dbce"



background = "#221c16"
foreground = "#e2dbce"
