[v1]
"bottom 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"fd-find 8.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"lefthk 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["lefthk"]
"lsd 0.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"pier 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["pier"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"stylua 0.12.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["stylua"]
"tealdeer 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
